swagger: '2.0'
info: {title: bottle-swagger, version: 1.0.0}
produces: [application/json]
consumes: [application/json]
definitions:
  Thing:
    properties:
      id: {type: string}
      name: {type: string}
    required: [id]
    type: object
paths:
  /thing:
    get:
      responses:
        '200':
          description: ''
          schema: {$ref: '#/definitions/Thing'}
    post:
      parameters:
      - in: body
        name: thing
        required: true
        schema: {$ref: '#/definitions/Thing'}
      responses:
        '200':
          description: ''
          schema: {$ref: '#/definitions/Thing'}
  "/thing/{thing_id}":
    get:
      parameters:
      - {in: path, name: thing_id, required: true, type: string}
      responses:
        '200':
          description: ''
          schema: {$ref: '#/definitions/Thing'}
  "/thing_query":
    get:
      parameters:
      - {in: query, name: thing_id, required: true, type: string}
      responses:
        '200':
          description: ''
          schema: {$ref: '#/definitions/Thing'}
  "/thing_header":
    get:
      parameters:
      - {in: header, name: thing_id, required: true, type: string}
      responses:
        '200':
          description: ''
          schema: {$ref: '#/definitions/Thing'}
  "/thing_formdata":
    post:
      consumes: ['application/x-www-form-urlencoded', 'multipart/form-data']
      parameters:
      - {in: formData, name: thing_id, required: true, type: string}
      responses:
        '200':
          description: ''
          schema: {$ref: '#/definitions/Thing'}
